name: Frontend-backend pipeline

on: 
  push: 
    branches: 
      dev


jobs:
  Frontend_Build_Image:
    runs-on: ubuntu-24.04
    # defaults:
    #   run:
    #     working-directory: ./frontend
    environment: production
    outputs:
      github-sha: ${{ steps.github-sha.outputs.github-sha }}

    steps:
      - name: Generate a SHA for Docker tag
        id: github-sha
        run: echo "github-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: "actions/checkout@v4"

      - name: Login in Docker
        uses: "docker/login-action@v3"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build docker image"
        uses: "docker/setup-buildx-action@v3"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ vars.FRONTEND_IMAGE_NAME }}:${{ steps.github-sha }}

  Backend_Build_Image:
    runs-on: ubuntu-24.04
    # defaults:
    #   run:
    #     working-directory: ./backend
    needs: Frontend_Build_Image
    env:
      github-sha: ${{ needs.Frontend_Build_Image.outputs.github-sha }}
    environment: production

    steps:
      - name: Generate a SHA for Docker tag
        id: github-sha
        run: echo "github-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: "actions/checkout@v4"

      - name: Login in Docker
        uses: "docker/login-action@v3"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build docker image"
        uses: "docker/setup-buildx-action@v3"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ vars.BACKEND_IMAGE_NAME }}:${{ steps.github-sha }}

  
  Deploy:
    runs-on: ubuntu-24.04
    environment: production
    needs:
      - Frontend_Build_Image
      - Backend_Build_Image
    env:
      github-sha: ${{ needs.Frontend_Build_Image.outputs.github-sha }}

    steps:
    - name: "Execute to SSH login"
      uses: "appleboy/ssh-action@v1"
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_SSH_KEY }}
        port: 22
        script: |
          ls
