name: Frontend-backend pipeline

on: 
  # workflow_dispatch: 
  #   inputs:
  #     environment:
  #       description: "select an environment to run"
  #       type: environment
  #       default: "dev"

  pull_request: 
    branches: [main]
  push: 
    branches: [dev, main]

concurrency: 
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/${{ vars.FRONTEND_IMAGE_NAME }}:${{ github.sha }}
  BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/${{ vars.BACKEND_IMAGE_NAME }}:${{ github.sha }}
  FRONTEND_IMAGE_LATEST: ${{ secrets.DOCKER_USERNAME }}/${{ vars.FRONTEND_IMAGE_NAME }}:latest
  BACKEND_IMAGE_LATEST: ${{ secrets.DOCKER_USERNAME }}/${{ vars.BACKEND_IMAGE_NAME }}:latest

jobs:

  Frontend_Build_Test:
    runs-on: ubuntu-24.04
    # if: ${{ github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' }}
    defaults:
      run:
        working-directory: ./frontend

    # strategy:
    #   matrix:
    #     node: [22,24]

    steps:
        
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Setup node action
        uses: actions/setup-node@v4
        with:
          # node-version: ${{ matrix.node }}
          node-version: 24
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Security scanning in npm
        run: npm audit > frontend-audit || true

      - name: Upload audit results
        uses: actions/upload-artifact@v4
        with:
          name: frontend-audit-${{ github.sha }}
          path: ./frontend/frontend-audit
          retention-days: 7
          if-no-files-found: warn


      - name: Install dependencies
        run: npm ci --loglevel verbose

      - name: Run lint test
        run: npm run lint || true

      # CI should NOT depend on production URL
      - name: Create .env file
        run: |
          echo "VITE_BASE_URL=http://localhost:8080" > .env

      - name: Run build
        run: npm run build

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist-${{ github.sha }}
          path: ./frontend/dist
          retention-days: 5
          if-no-files-found: error
          compression-level: 6

      - name: Run unit tests
        run: npm run test || true

  Backend_Build_Test:
    runs-on: ubuntu-24.04
    # if: ${{ github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' }}
    defaults:
      run:
        working-directory: ./backend

    # strategy:
    #   matrix:
    #     node: [22,24]

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Setup node action
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json

      - name: Security scanning in npm
        run: npm audit > backend-audit || true

      - name: Upload audit results
        uses: actions/upload-artifact@v4
        with:
          name: backend-audit-${{ github.sha }}
          path: ./backend/backend-audit
          retention-days: 7
          if-no-files-found: warn

      - name: Install dependencies
        run: npm ci --loglevel verbose

      - name: Run lint test
        run: npm run lint || true

      - name: Run build
        run: npm run build

      - name: Run unit tests
        run: npm run test || true

  Frontend_Build_Image:
    runs-on: ubuntu-24.04
    needs: Frontend_Build_Test

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build and push
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: true
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend
          tags: |
            ${{ env.FRONTEND_IMAGE }}
            ${{ env.FRONTEND_IMAGE_LATEST }}
          build-args: |
            VITE_CLOUDINARY_CLOUD_NAME=${{ vars.VITE_CLOUDINARY_CLOUD_NAME }}
            VITE_CLOUDINARY_UPLOAD_PRESET=${{ vars.VITE_CLOUDINARY_UPLOAD_PRESET }}
          #   VITE_BASE_URL=${{ github.ref == 'refs/heads/main' && format('http://{0}:{1}', secrets.HOST, secrets.PORT) || 'http://backend:8080' }}

  Backend_Build_Image:
    runs-on: ubuntu-24.04
    needs: Backend_Build_Test

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build and push
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          push: true
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend
          tags: |
            ${{ env.BACKEND_IMAGE }}
            ${{ env.BACKEND_IMAGE_LATEST }}

  Run_Integration_Test:
    runs-on: ubuntu-24.04
    needs: [Frontend_Build_Test, Backend_Build_Image]
    if: ${{ github.ref == 'refs/heads/dev' || github.event_name == 'pull_request' }}

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Generate a .env file
        run: |
          cat <<EOF > .env
          PORT=8080
          DB_HOST=database
          DB_PORT=5432
          DB_NAME=admindb
          DB_USER=root
          DB_PASSWORD=admin123
          VITE_BASE_URL=http://backend:8080
          HOST=localhost
          EOF

      - name: Pull the latest image for backend
        run: |
          # docker pull ${{ env.FRONTEND_IMAGE }}
          docker pull ${{ env.BACKEND_IMAGE }}

      - name: Start a docker compose
        run: docker compose up -d
        env:
          FRONTEND_IMAGE: ${{ env.FRONTEND_IMAGE }}
          BACKEND_IMAGE: ${{ env.BACKEND_IMAGE }}

      - name: Wait for backend to start
        run: |
          for i in {1..20}; do
            if curl -f http://localhost:8080/health; then
              echo "Backend is up"
              exit 0
            fi
            sleep 3
          done
          
          echo "Backend failed to start"
          docker logs $(docker ps -q)
          exit 1

      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist-${{ github.sha }}
          path: ./frontend/dist

      - name: Test integration test
        run: |
          cd frontend
          npm ci 
          npm run test:integration
        env:
          VITE_BASE_URL: http://localhost:8080   

      - name: Docker cleanup
        run: docker compose down

  Deploy:
    runs-on: ubuntu-24.04
    environment: production
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - Frontend_Build_Image
      - Backend_Build_Image

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Copy compose file into EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          source: 'compose.yaml'
          target: '/home/ubuntu'

      - name: Update new Compose file
        uses: "appleboy/ssh-action@v1"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cat <<EOF > .env
            PORT=${{ secrets.PORT }}

            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}

            FRONTEND_IMAGE=${{ env.FRONTEND_IMAGE }}
            BACKEND_IMAGE=${{ env.BACKEND_IMAGE }}
            VITE_BASE_URL=http://${{ secrets.HOST }}:${{ secrets.PORT }}

            EOF
              

              docker pull ${{ env.FRONTEND_IMAGE }}
              docker pull ${{ env.BACKEND_IMAGE }}

              docker compose --env-file .env down
              docker compose --env-file .env up -d --remove-orphans

  Smoke_Testing:
    runs-on: ubuntu-24.04
    environment: production
    needs: Deploy

    steps:
      - run: ping ${{ secrets.HOST }} -c 10 || true
      - run: curl http://${{ secrets.HOST }}:${{ secrets.PORT }}
      - run: curl http://${{ secrets.HOST }}
