name: Frontend-backend pipeline

on: 
  push: 
    branches: 
      dev

concurrency: 
  group: idk
  cancel-in-progress: true

env:
  FRONTEND_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ vars.FRONTEND_IMAGE_NAME }}:${{ github.sha }}
  BACKEND_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ vars.BACKEND_IMAGE_NAME }}:${{ github.sha }}
  FRONTEND_IMAGE_NAME_LATEST: ${{ secrets.DOCKER_USERNAME }}/${{ vars.FRONTEND_IMAGE_NAME }}:latest
  BACKEND_IMAGE_NAME_LATEST: ${{ secrets.DOCKER_USERNAME }}/${{ vars.BACKEND_IMAGE_NAME }}:latest

jobs:
  Frontend_Build_Test:
    runs-on: ubuntu-24.04
    environment: production
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        index: [1,2,3]

    steps:
      - name: Clone the frontend repo 
        uses: "actions/checkout@v4"

      # - run: echo ${{ matrix.index }}

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Dependencies scanning
        run: "npm audit"

      - name: Install the dependencies
        id: install
        run: "npm ci --loglevel verbose"

      - name: Checking linting
        run: "npm run lint || true"

      - name: Make .env
        run: |
          cat <<EOF > .env
          VITE_BASE_URL=http://${{ secrets.HOST }}:${{ secrets.PORT }}
          EOF

      - name: Build the code
        run: "npm run build"

      - name: Check Unit Testing
        run: "npm run test || true"

      # - name: Upload artifacts
      #   uses: "actions/upload-artifact@v6" 
      #   if: ${{ matrix.index == 1 }}
      #   with:
      #     name: frontend-build
      #     path: |
      #       ./frontend/dist/
      #       ./frontend/Dockerfile

  Backend_Build_Test:
    runs-on: ubuntu-24.04
    environment: production
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Clone the frontend repo 
        uses: "actions/checkout@v4"

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json

      - name: Dependencies scanning
        run: "npm audit"

      - name: Install the dependencies
        run: "npm ci --loglevel verbose"

      - name: Checking linting
        run: "npm run lint || true"

      - name: Build the code
        run: "npm run build"

      # - name: Upload artifacts
      #   uses: "actions/upload-artifact@v6" 
      #   with:
      #     name: backend-build
      #     path: |
      #       ./backend/dist/
      #       ./backend/Dockerfile

      - name: Check Unit Testing
        run: "npm run test || true"

  # Generate_Github_SHA:
  #   runs-on: ubuntu-24.04
  #   outputs:
  #     github-sha: ${{ steps.github-sha.outputs.github-sha }}
  #
  #   steps:
  #     - name: Clone the repo
  #       uses: "actions/checkout@v4"
  #
  #     - name: Generate a SHA for Docker tag
  #       id: github-sha
  #       run: echo "github-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  Frontend_Build_Image:
    runs-on: ubuntu-24.04
    needs: Frontend_Build_Test

    # env:
    #   github-sha: ${{ needs.Generate_Github_SHA.outputs.github-sha }}
    defaults:
      run:
        working-directory: ./frontend

    environment: production

    steps:
      - name: Checkout code
        uses: "actions/checkout@v4"

      # - name: Download the artifacts
      #   uses: "actions/download-artifact@v8"
      #   with:
      #     name: frontend-build
      #     path: dist
      #

      - name: Login in Docker
        uses: "docker/login-action@v3"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build docker image"
        uses: "docker/setup-buildx-action@v3"

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: true
          cache-from: type=gha,scope=frontend # stores cache in GitHub cache backend
          cache-to: type=gha,mode=max,scope=frontend # restore cache in next run
          tags: |
            ${{ env.FRONTEND_IMAGE_NAME }}
            ${{ env.FRONTEND_IMAGE_NAME_LATEST }} 
          build-args: |
            VITE_BASE_URL=http://${{ secrets.HOST }}:${{ secrets.PORT }}

      # - name: Docker image scanning 
      #   uses: aquasecurity/trivy-action@0.33.1
      #   with:
      #     image-ref: 'docker.io/${{ env.FRONTEND_IMAGE_NAME }}'
      #     format: 'table'
      #     exit-code: 0
      #     severity: CRITICAL,HIGH

  Backend_Build_Image:
    runs-on: ubuntu-24.04

    # defaults:
    #   run:
    #     working-directory: ./backend
    # needs: Generate_Github_SHA
    # env:
    #   github-sha: ${{ needs.Generate_Github_SHA.outputs.github-sha }}

    environment: production
    needs: Backend_Build_Test

    steps:
      - name: Checkout code
        uses: "actions/checkout@v4"

      # - name: Download the artifacts
      #   uses: "actions/download-artifact@v8"
      #   with:
      #     name: backend-build
      #     path: dist

      - name: Login in Docker
        uses: "docker/login-action@v3"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: "Build docker image"
        uses: "docker/setup-buildx-action@v3"

      - name: Build and push
        uses: docker/build-push-action@v7

        with:
          context: ./backend
          push: true
          cache-from: type=gha,scope=backend # stores cache in GitHub cache backend
          cache-to: type=gha,mode=max,scope=backend # restore cache in next run, Mode could be max, min
          # url: 
          # repository: 
          tags: |
            ${{ env.BACKEND_IMAGE_NAME }}
            ${{ env.BACKEND_IMAGE_NAME_LATEST }} 

      # - name: Docker image scanning 
      #   uses: aquasecurity/trivy-action@0.33.1
      #   with:
      #     image-ref: 'docker.io/${{ env.BACKEND_IMAGE_NAME }}'
      #     format: 'table'
      #     exit-code: 0
      #     severity: CRITICAL,HIGH
  
  Deploy:
    runs-on: ubuntu-24.04
    environment: production
    needs:
      - Frontend_Build_Image
      - Backend_Build_Image

    # env:
    #   github-sha: ${{ needs.Generate_Github_SHA.outputs.github-sha }}

    steps:
    - name: Clone the repo
      uses: "actions/checkout@v4"

    - name: Copy compose.yaml to server
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_SSH_KEY }}
        port: 22
        source: 'compose.yaml'
        target: '/home/ubuntu'

    # - name: Update new Compose file
    #   uses: appleboy/ssh-action@v1
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.PRIVATE_SSH_KEY }}
    #     port: 22
    #     script: |
    #       docker pull ${{ env.FRONTEND_IMAGE_NAME }}
    #       docker pull ${{ env.BACKEND_IMAGE_NAME }}
    
        # sed -i "s|product-frontend:latest|${{ env.FRONTEND_IMAGE_NAME }}|g" ~/compose.yaml
        # sed -i "s|product-backend:latest|${{ env.BACKEND_IMAGE_NAME }}|g" ~/compose.yaml
    
    - name: Update new Compose file
      uses: "appleboy/ssh-action@v1"
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_SSH_KEY }}
        port: 22
        script: |
          cat <<EOF > .env
          PORT=${{ secrets.PORT }}
    
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
    
          VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}
    
          HOST=${{ secrets.HOST }}
          EOF

            cat .env

            docker pull ${{ env.FRONTEND_IMAGE_NAME_LATEST }}
            docker pull ${{ env.BACKEND_IMAGE_NAME_LATEST }}
    
            docker compose down
            docker compose up -d --remove-orphans

  Smoke_Testing:
    runs-on: self-hosted
    environment: production
    needs: Deploy

    steps:
      - name: Check system is up
        run: ping ${{ secrets.HOST }} -c 10 || true

      - name: Check backend API
        run: curl http://${{ secrets.HOST }}:${{ secrets.PORT }}

      - name: Check frontend API
        run: curl http://${{ secrets.HOST }}

