name: Testing pipeline


on:
  push:
    branches: 
      dev

defaults:
  run:
    shell: nu {0}

jobs:
  Masking-env:
    runs-on: self-hosted
    
    steps:

    - run: ls /

    - name: Generate a env
      run: |
        SECRET="Ohhh, FAA"
        echo "::add-mask::$SECRET"
        echo "SECRET_VALUE=$SECRET"
