name: Testing pipeline


on:
  workflow_dispatch: 
  # push:
  #   branches: 
  #     dev

# defaults:
#   run:
#     shell: nu {0}

jobs:
  Masking-env:
    runs-on: ubuntu-24.04
    
    steps:

    # - run: echo "${{ toJson(github) }}"

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
        timeout-minutes: 30

    # - name: Generate a env
    #   run: |
    #     SECRET="Ohhh, FAA"
    #     echo "::add-mask::$SECRET"
    #     echo "SECRET_VALUE=$SECRET"
