name: Testing pipeline


on:
  workflow_dispatch: 
  # push:
  #   branches: 
  #     dev

# defaults:
#   run:
#     shell: nu {0}

jobs:
  Masking-env:
    runs-on: ubuntu-24.04
    # outputs:
    #   ssh-command: ${{ steps.tmate.outputs.ssh-command }}
    #   ssh-address: ${{ steps.tmate.outputs.ssh-address }}

    steps:
    - name: Clone the repo
      uses: "actions/checkout@v4"

    - run: echo "/my/custom/bin" >> $GITHUB_PATH
    - run: echo $GITHUB_PATH

    - run: echo "## Build Summary " >> $GITHUB_STEP_SUMMARY

    # - run: echo "${{ toJson(github) }}"

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      id: tmate
      with:
        # tmate-server-host: ssh.tmate.io
        # tmate-server-port: 22
        # tmate-server-rsa-fingerprint: SHA256:Hthk2T/M/Ivqfk1YYUn5ijC2Att3+UPzD7Rn72P5VWs
        # tmate-server-ed25519-fingerprint: SHA256:jfttvoypkHiQYUqUCwKeqd9d1fJj/ZiQlFOHVl6E9sI
        limit-access-to-actor: true
        # timeout-minutes: 30

    - name: Echo things
      run: |
        echo ${{ steps.tmate.outputs.ssh-command }}
        echo ${{ steps.tmate.outputs.ssh-address }}


    # - name: Generate a env
    #   run: |
    #     SECRET="Ohhh, FAA"
    #     echo "::add-mask::$SECRET"
    #     echo "SECRET_VALUE=$SECRET"
